import Navbar from "../components/layout/Navbar";

export default function TermsAndConditionsPage() {
  const data = [
    {
      title: "Acceptance of Terms",
      content: (
        <p>
          By accessing or using Vector, you agree to be bound by these Terms
          and Conditions. If you do not agree, please do not use the platform.
          These terms apply to all users, including free and paid subscribers.
        </p>
      ),
    },
    {
      title: "Eligibility & Account Registration",
      content: (
        <ul className="list-disc space-y-2 pl-5">
          <li>You must be at least 13 years old to use Vector.</li>
          <li>
            You are responsible for maintaining the confidentiality of your
            account credentials.
          </li>
          <li>
            You agree to provide accurate and complete information during
            registration and onboarding.
          </li>
          <li>
            You are responsible for all activity that occurs under your
            account.
          </li>
        </ul>
      ),
    },
    {
      title: "Platform Services",
      content: (
        <p>
          Vector provides AI-powered learning roadmaps, daily tasks, progress
          tracking, focus tools, community features, and related educational
          services. Features may change, improve, or be discontinued as we
          continue to develop the platform.
        </p>
      ),
    },
    {
      title: "AI-Generated Content",
      content: (
        <p>
          Roadmaps, tasks, recommendations, and insights generated by our AI
          are provided for guidance and educational purposes only. They do not
          constitute professional, legal, financial, or career advice. You are
          solely responsible for how you use AI-generated content and for
          verifying its accuracy and suitability for your goals.
        </p>
      ),
    },
    {
      title: "Acceptable Use",
      content: (
        <ul className="list-disc space-y-2 pl-5">
          <li>Use Vector only for lawful and intended purposes.</li>
          <li>
            Do not harass, abuse, or harm other users in community features.
          </li>
          <li>
            Do not attempt to reverse engineer, scrape, or disrupt the
            platform.
          </li>
          <li>
            Do not upload malicious code or content that violates intellectual
            property or privacy rights.
          </li>
          <li>
            Do not share your account or use the service to spam or mislead
            others.
          </li>
        </ul>
      ),
    },
    {
      title: "Community & Organizations",
      content: (
        <p>
          When you join organizations or participate in community features,
          you agree to follow community guidelines and respect other members.
          Content you share in public or organization spaces may be visible to
          other members depending on your settings and the organization&apos;s
          configuration.
        </p>
      ),
    },
    {
      title: "Subscriptions & Payments",
      content: (
        <p>
          Paid plans, billing cycles, and pricing are displayed at checkout.
          By subscribing, you authorize us to charge your selected payment
          method. Refunds and cancellations are governed by our Cancellation
          and Refund Policy. We may update pricing with reasonable notice
          where required.
        </p>
      ),
    },
    {
      title: "Intellectual Property",
      content: (
        <p>
          Vector, including its branding, software, design, and content, is
          owned by Moveforward Private Limited or its licensors. You retain
          ownership of content you submit, but grant us a limited license to
          host, process, and display it as needed to operate the platform.
        </p>
      ),
    },
    {
      title: "Termination",
      content: (
        <p>
          You may stop using Vector and delete your account at any time. We
          may suspend or terminate access if you violate these terms or if
          continued use poses a security, legal, or operational risk. Upon
          termination, your right to use the platform ends, subject to any
          legal obligations that survive.
        </p>
      ),
    },
    {
      title: "Disclaimer & Limitation of Liability",
      content: (
        <p>
          Vector is provided on an &quot;as is&quot; and &quot;as available&quot;
          basis without warranties of uninterrupted or error-free service. To
          the fullest extent permitted by law, Moveforward Private Limited is
          not liable for indirect, incidental, or consequential damages arising
          from your use of the platform.
        </p>
      ),
    },
    {
      title: "Changes to These Terms",
      content: (
        <p>
          We may update these Terms and Conditions from time to time. Material
          changes will be communicated through the platform or via email where
          appropriate. Continued use after updates constitutes acceptance of
          the revised terms.
        </p>
      ),
    },
    {
      title: "Contact",
      content: (
        <p>
          Questions about these terms?
          <br />
          Contact us at:
          <span className="ml-2 text-orange-400">
            vectorofficalorg@gmail.com
          </span>
        </p>
      ),
    },
  ];

  return (
    <main className="min-h-screen bg-black text-white">
      <Navbar />

      <div className="mx-auto max-w-6xl px-6 py-24">
        {/* HERO */}

        <div className="mb-8">
          <div className="inline-flex rounded-full border border-orange-500/30 bg-orange-500/10 px-4 py-2 text-sm text-orange-400">
            Legal
          </div>

          <div className="mt-4 text-4xl font-bold tracking-tight">
            Terms and Conditions - Vector
          </div>
          <p className="mt-4 max-w-3xl text-xl text-zinc-400 leading-relaxed">
            These terms govern your access to and use of Vector, including
            AI-powered roadmaps, progress tracking, community features, and
            related services provided by Moveforward Private Limited.
          </p>
        </div>

        {/* CONTENT */}

        <div className="space-y-8">
          {data.map((section, index) => (
            <div
              key={section.title}
              className="rounded-3xl border border-white/10 bg-zinc-950 p-6"
            >
              <h2 className="text-2xl font">
                <span className="mr-3 text-white/40">{index + 1}.</span>
                {section.title}
              </h2>

              <div className="mt-3 text-zinc-400 leading-relaxed">
                {section.content}
              </div>
            </div>
          ))}
        </div>
      </div>
    </main>
  );
}
